---
version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: pysqlclient
    # command: >
    # tail -f /dev/null
  db:
    image: mysql:8.0
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: >
      mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
