name: "test-python-lint"

on: [pull_request, push]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # install packages
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==22.3.0 isort==5.10.1 flake8==4.0.1
      # execute tests ~ Formatter ~
      - name: test isort
        run: isort --check --diff *.py src/*.py
      - name: test black
        run: black --check --diff *.py src/*.py
      - name: test flake8
        run: flake8 --ignore=E501 *.py src/*.py
  style_docker:
    run-on: ubuntu-latest
    container:
      image: hadolint/hadolint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: dockerfile linter
        run: |
         docker run --rm -i hadolint/hadolint < Dockerfile

