---

name: "test-lint"

on:  # yamllint disable-line rule:truthy
  pull_request:

jobs:
  python_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # install packages
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==22.3.0 isort==5.10.1 flake8==4.0.1 mypy==0.971
      # execute tests ~ Formatter ~
      - name: test isort
        # run: isort --check --diff *.py src/*.py
        run: isort --settings-path config *.py src/
      - name: test black
        run: black --check --diff *.py src/*.py
      - name: test flake8
        run: flake8 --ignore=E501 *.py src/*.py
      - name: test mypy
        run: mypy main.py --config-file config/mypy.cfg
      - name: test xenon
        run: xenon -b A -m A -a A main.py src/
  docker_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: ./Dockerfile
          ignore: DL3008,DL3015,DL3013,DL3059
  yaml_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows/* docker-compose.yml
          config_data: |
            rules:
              line-length:
                max: 90
